# Basics of Tensorflow

### How Tensorflow Works?
Tensorflow defines computations as graphs, and these are made with operations(Ops). So In general working with tensorflow is same as defining a series of operations in a Graph. 

Import Tensorflow Library

In [32]:
import tensorflow as tf

### Building a Graph

In [2]:
graph1 = tf.Graph()
graph1

To make computations with tensorflow. it's necessary to make operations.
So call the tensorflow function that constructs new tf.oprations and tf.tensor objects and add them to graph1

In [8]:
with graph1.as_default():
    a = tf.constant([23], name = "constant_a")
    b = tf.constant([34], name = "constant_b")

Now run the graph into a Session to find the value of a and b

In [9]:
sess_a = tf.Session(graph = graph1)
result_a = sess_a.run(a)
print(result_a)
sess_a.close()

[23]


Similarly to find the value of b

In [10]:
sess_b = tf.Session(graph = graph1)
result_b = sess_b.run(b)
print(result_b)
sess_b.close()

[34]


Make an operation over these two Tensor function tf.add() that adds two tensors (c = a + b)

In [11]:
with graph1.as_default():
    c = tf.add(a,b)

To find the value of c, run it into the Session

In [12]:
sess_c = tf.Session(graph = graph1)
result_c = sess_c.run(c)
print(result_c)
sess_c.close()

[57]


To avoid having to close, sessions everytime, Define it in a "with" block. So after running the "with" block, the Session will close automatically 

In [13]:
with tf.Session(graph = graph1) as sess:
    result = sess.run(c)
    print(result)

[57]


### Defining Multi-Dimensional arrays using Tensorflow

In [14]:
graph2 = tf.Graph()

In [15]:
with graph2.as_default():
    Scalar = tf.constant(34)
    Vector = tf.constant([1,2,3])
    Matrix = tf.constant([[1,2,4],[5,6,7],[45,67,89]])
    Tensor = tf.constant([[1,2,4],[5,6,7],[45,67,89],[1,2,4],[5,6,7],[45,67,89],[1,2,4],[5,6,7],[45,67,89]])
    

To find the values of the constant defined to the graph, run into the Session.

In [30]:
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print("Scalar:")
    print(result)
    
    result = sess.run(Vector)
    print("Vector:")
    print(result)
    
    result = sess.run(Matrix)
    print("Matrix:")
    print(result)
    
    result = sess.run(Tensor)
    print("Tensor:")
    print(result)

Scalar:
34
Vector:
[1 2 3]
Matrix:
[[ 1  2  4]
 [ 5  6  7]
 [45 67 89]]
Tensor:
[[ 1  2  4]
 [ 5  6  7]
 [45 67 89]
 [ 1  2  4]
 [ 5  6  7]
 [45 67 89]
 [ 1  2  4]
 [ 5  6  7]
 [45 67 89]]


In [17]:
Scalar.shape

TensorShape([])

In [18]:
Vector.shape

TensorShape([Dimension(3)])

In [19]:
Matrix.shape

TensorShape([Dimension(3), Dimension(3)])

In [20]:
Tensor.shape

TensorShape([Dimension(9), Dimension(3)])

### Mathematical Operations

In [21]:
graph3 = tf.Graph()

In [23]:
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,4],[5,6,7],[45,67,89]])
    Matrix_two = tf.constant([[13,23,43],[54,64,7],[45,67,89]])
    
    
    add_1 = tf.add(Matrix_one, Matrix_two)
    add_2 = Matrix_one + Matrix_two

In [26]:
with tf.Session(graph = graph3) as sess:
    result = sess.run(add_1)
    print("Tensor operation:")
    print(result)
    
    result = sess.run(add_2)
    print("Normal operation:")
    print(result)

Tensor operation:
[[ 14  25  47]
 [ 59  70  14]
 [ 90 134 178]]
Normal operation:
[[ 14  25  47]
 [ 59  70  14]
 [ 90 134 178]]


In [41]:
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,4],[5,6,7],[45,67,89]])
    Matrix_two = tf.constant([[13,23,43],[54,64,7],[45,67,89]])
    
    mul = tf.matmul(Matrix_one, Matrix_two)
    sub = tf.subtract(Matrix_one, Matrix_two)

In [42]:
with tf.Session(graph = graph3) as sess:
    result = sess.run(mul)
    print("Multiplication Result:")
    print(result)

Multiplication Result:
[[  301   419   413]
 [  704   968   880]
 [ 8208 11286 10325]]


In [44]:
with tf.Session(graph = graph3) as sess:
    result = sess.run(sub)
    print("Subtracted result:")
    print(result)
    

Subtracted result:
[[-12 -21 -39]
 [-49 -58   0]
 [  0   0   0]]


### Variables

Why do we need Variables?
+ It's possible to update the value of a variable through each run, it's not possible with tensor

How to define a variable?
+ Using the command tf.Variable()
+ To use variables in a computation graph it is necessary to initialize them before running the graph in a session.
+ It is done by tf.global_variables_initializer()

To update the value of a variable, run an assign operation that assigns a value to the variable

In [31]:
v = tf.Variable(0)

create a variable that increases one unit at a time.
To do this use tf.assign(reference_variable, value_to_update)

In [33]:
update = tf.assign(v,v+1)

Varables is to be initialized by running an initialisation operation after having launched the graph.

In [34]:
init_op = tf.global_variables_initializer()

start a session to run the graph.
+ first initialize the variables
+ then run operation of updating the state variable and print the result after each update

In [35]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(v))
    
    for _ in range(3):
        session.run(update)
        print(session.run(v))

0
1
2
3


### Placeholders

Placeholders are used to feed the data to Tensorflow graph from outside a graph.

Placeholders can be seen as "holes" in the model which to pass the data to. It can be created by tf.placeholder(datatype).

In [36]:
a = tf.placeholder(tf.float32)

In [37]:
b = a * 2

now there is a hole in the model to pass the data, it is necessary to pass data when the session is going to initialize, otherwise there will be an error

In [38]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict = {a: 3.5})
    print(result)

7.0


In [39]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict = {a: 5})
    print(result)

10.0


its is allowed to pass any kind of tensors

In [40]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


tf.nn.sigmoid is an activation function, it's a litthis function helps learning models to evaluate what kind of information is good or not.